version: '3'

services:
  db:
    image: mysql:8
    container_name: mysqldb_great_pro_test_task
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_USER: test
      MYSQL_PASSWORD: testpasswd
    volumes:
      # Mysql database and config will be persisted to /mysql_volume/
      - ./mysql_volume:/var/lib/mysql
      # If you want to run a initial query after container start
      - ./config_override/data/dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13306:3306"
  php81_web:
    build:
      context: ./
      dockerfile: ./dockerfiles/php8.1/Dockerfile
    image: php81_web
    container_name: php81_web_great_pro_test_task
    depends_on:
      - db
    # If you want to run specific bash command after container start
    # command: >
    #  bash -c "echo 'You can runyour own command here'
    #  && echo 'multiple command too'"
    volumes:
      # web files will be persisted to /web_volume/
      - ../:/var/www/html/
      # override and persist php.ini config
      - ./config_override/php81.ini:/usr/local/etc/php/php.ini
      # override and persist apache config
      - ./config_override/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      # if you need ioncube loader, it will be loaded from php.ini
    ports:
      - "11080:80"
      - "19003:9003"
    stdin_open: true
    tty: true
